---

- name: Create SSLO SSL Configuration
  hosts: all
  gather_facts: False

  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: "34.234.171.124"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_httpapi_password: "f5Twister!"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

    snort1_host: "10.0.3.38"
    snort2_host: "10.0.4.41"
    webapp_pool: "192.168.1.38"

    ## ======================= ##

    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_httpapi_password }}"
      server_port: "{{ ansible_httpapi_port }}"
      validate_certs: no

  tasks:
    ## webapp pool
    - name: Create webapp pool
      bigip_pool:
        provider: "{{ provider }}"
        name: webapp
      delegate_to: localhost

    - name: Add member to webapp pool
      bigip_pool_member:
        provider: "{{ provider }}"
        pool: webapp
        host: "{{ webapp_pool }}"
        port: 443
      delegate_to: localhost

    ## SSL Configuration
    - name: Create an SSLO SSL config with reverse proxy
      bigip_sslo_config_ssl:
        name: "sslconfig"
        client_settings:
          proxy_type: "reverse"
          cert: "/Common/default.crt"
          key: "/Common/default.key"

    ## Inline L3 service 1
    - name: SSLO LAYER 3 (SNORT1)
      bigip_sslo_service_layer3:
        name: "SNORT1"
        devices_to:
          vlan: "/Common/dmz1"
          self_ip: "10.0.3.7"
          netmask: "255.255.255.128"
        devices_from:
          vlan: "/Common/dmz2"
          self_ip: "10.0.3.245"
          netmask: "255.255.255.128"
        devices:
        - ip: "{{ snort1_host }}"

    ## Inline L3 service 2
    - name: SSLO LAYER 3 (SNORT2)
      bigip_sslo_service_layer3:
        name: "SNORT2"
        devices_to:
          vlan: "/Common/dmz3"
          self_ip: "10.0.4.7"
          netmask: "255.255.255.128"
        devices_from:
          vlan: "/Common/dmz4"
          self_ip: "10.0.4.245"
          netmask: "255.255.255.128"
        devices:
        - ip: "{{ snort2_host }}"
    
    ## Service chain 1
    - name: Create SSLO service chain
      bigip_sslo_config_service_chain:
        name: "service_chain_1"
        services:
        - service_name: "SNORT1"
          type: "L3"
          ip_family: "ipv4"

    ## Service chain 2
    - name: Create SSLO service chain
      bigip_sslo_config_service_chain:
        name: "service_chain_2"
        services:
        - service_name: "SNORT2"
          type: "L3"
          ip_family: "ipv4"

    ## Security Policy
    - name: SSLO config policy
      bigip_sslo_config_policy:
        name: "sslopolicy"
        policy_consumer: "inbound"
        policy_rules:
        - name: "all_ssl_traffic"
          policy_action: "allow"
          ssl_forwardproxy_action: "intercept"
          service_chain: "ssloSC_service_chain_1"
          conditions:
          - condition_type: "server_port_match"
            condition_option_ports:
            - "443"

    ## Topology
    - name: Create SSLO Topology
      bigip_sslo_config_topology:
        name: "l3inboundapp"
        topology_type: "inbound_l3"
        dest: "10.0.2.200/32"
        port: 443
        ssl_settings: "sslconfig"
        security_policy: "ssloP_sslopolicy"
        vlans:
        - "/Common/external"
        snat: "automap"
        pool: "/Common/webapp"

